version: '3'

services:
  jfrog:
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    ports:
      - '8081:8081'
    deploy:
      replicas: 4
#      resources:
#        limits:
#          cpus: '0.01'
#          memory: 1024M
#        reservations:
#         cpus: '0.01'
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=96.126.124.241
      - DB_PORT=5432
      - DB_USER=artifactory
      - DB_NAME=artifactory
      - DB_PASSWORD=password
